spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee?useSSL=false
    username: root
    password: 1517
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081
greeting:
  message: "I'm UP"